# Generated by Django 5.2.5 on 2025-09-14 12:35

from django.db import migrations, models
from django.contrib.auth.models import User

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dailyadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                
                ('grocery', models.CharField(max_length=5000)),
                ('onlinepayment', models.CharField(max_length=5000)),
                ('datetime', models.CharField()),
                ('total', models.CharField()),
            ],
        ),
    ]
