# Generated by Django 5.2.5 on 2025-09-20 12:46

from django.db import migrations, models
from django.contrib.auth.models import User


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monthlyadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                
                ('income', models.CharField()),
                ('rent', models.CharField()),
                ('Utilities', models.CharField()),
                ('Subscriptions', models.CharField()),
                ('food', models.CharField()),
                ('transport', models.CharField()),
                ('shopping', models.CharField()),
                ('bank', models.CharField()),
                ('SIP', models.CharField()),
                ('Festival', models.CharField()),
                ('Medical', models.CharField()),
                ('month', models.CharField()),
                ('date', models.DateField()),
                ('totalspent', models.CharField()),
                ('fixed_expenses', models.CharField()),
                ('varaiable_expenses', models.CharField()),
                ('saving', models.CharField()),
                ('sessional', models.CharField()),
            ],
        ),
    ]
