# Generated by Django 5.2.5 on 2025-09-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_monthlyadd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyadd',
            name='date',
        ),
    ]
