# Generated by Django 5.2.5 on 2025-09-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_remove_monthlyadd_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyadd',
            name='Subscriptions',
            field=models.CharField(max_length=50),
        ),
    ]
